services:
  - type: web
    name: library-management-api
    runtime: docker
    rootDir: library-management
    plan: free
    dockerfilePath: ./library-management/Dockerfile
    dockerContext: ./library-management
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGIN_PATTERNS
        sync: false
